#!/usr/bin/env php
<?php
SCli::existParameter($argv);

if ($argv[1] == "controller" || $argv[1] == "c")
    SCli::createController($argv);
else if ($argv[1] == "model" || $argv[1] == "m")
    SCli::createModel($argv);
else if ($argv[1] == "cm") {
    SCli::createController($argv);
    SCli::createModel($argv);
}
else if ($argv[1] == "mi" || $argv[1] == "migration")
    SCli::createMigration($argv);
else if ($argv[1] == "migrate" ||$argv[1] == "do:migrate")
    SCli::migrate($argv);
else if ($argv[1] == "help" || $argv[1] == "h")
    SCli::help();
else 
    echo "Parameter not allowed\n";

class SCli
{   
    private static $pathController = "application/controllers/";
    private static $pathView = "application/views/";
    private static $pathModel = "application/models/";
    private static $pathMigration = "application/migrations/";
    private static $scliMigrate = "Sclimigrate";

    public static function existParameter($argv)
    {
        if (count($argv) == 1) {
            echo "Missing parameter\n";
            exit();
        }
    }

    public static function help()
    {
        $help = "\n***********************************\n";
        $help .= "Available commands\n\n";
        $help .= "- Create Controller\n";
        $help .= "  \$ php scli c name_your_controller\n";
        $help .= "    or\n";
        $help .= "  \$ php scli controller name_your_controller\n\n";
        $help .= "- Create Model\n";
        $help .= "  \$ php scli m name_your_model\n";
        $help .= "    or\n";
        $help .= "  \$ php scli model name_your_model\n\n";
        $help .= "- Create Migration\n";
        $help .= "  \$ php scli mi name_your_migration\n";
        $help .= "    or\n";
        $help .= "  \$ php scli migration name_your_migration\n\n";
        $help .= "- Run last migration\n";
        $help .= "  \$ php scli migrate\n";
        $help .= "    or\n";
        $help .= "  \$ php scli do:migrate\n\n";
        $help .= "- Run a specific version of the migration\n";
        $help .= "  \$ php scli migrate value (sequential or timestamp)\n";
        $help .= "    or\n";
        $help .= "  \$ php scli do:migrate value (sequential or timestamp)\n";
        $help .= "\n***********************************\n";

        echo $help;
    }

    private static function fileSCliMigrateExist() {
        if (!file_exists(self::$pathController.self::$scliMigrate.".php")) {
            $fileMigrate = fopen(self::$pathController . self::$scliMigrate . ".php", "w") or die("Unable to open file!");

            $txt = "<?php\n";
            $txt .= "defined('BASEPATH') OR exit('No direct script access allowed');\n\n";
            $txt .= "class ". self::$scliMigrate ." extends CI_Controller {\n\n";
            $txt .= "   public function index(\$version = null)\n";
            $txt .= "   {\n";
            $txt .= "       \$this->load->library('migration');\n\n";
            $txt .= "       if (\$version != null) \n";
            $txt .= "       {\n";
            $txt .= "           if(!\$this->migration->version(\$version))\n";
            $txt .= "           {\n";
            $txt .= "               echo \$this->migration->error_string();\n";
            $txt .= "           }\n";
            $txt .= "           else\n";
            $txt .= "           {\n";
            $txt .= "               echo 'Successful Migration! - Version: ' . \$version;\n";
            $txt .= "           }\n";
            $txt .= "       }\n";
            $txt .= "       else\n";
            $txt .= "       {\n";
            $txt .= "           if(!\$this->migration->latest())\n";
            $txt .= "           {\n";
            $txt .= "               echo \$this->migration->error_string();\n";
            $txt .= "           }\n";
            $txt .= "           else\n";
            $txt .= "           {\n";
            $txt .= "               echo 'Successful Migration!';\n";
            $txt .= "           }\n";
            $txt .= "       }\n";
            $txt .= "   }\n";
            $txt .= "}";
            
            fwrite($fileMigrate, $txt);
            fclose($fileMigrate);
        }
    }

    public static function migrate($argv)
    {
        self::fileSCliMigrateExist();

        if (isset($argv[2])) {
            $output = shell_exec("php index.php ". self::$scliMigrate ." index " . $argv[2]);
            echo $output . "\n";
        } else {
            $output = shell_exec("php index.php ". self::$scliMigrate ." index");
            echo $output . "\n";
        }
    }

    public static function createMigration($argv)
    {
        if (!isset($argv[2])) {
            echo "Missing Migration name\n";
            exit();
        }

        if (!file_exists(self::$pathMigration)) {
            mkdir(self::$pathMigration, 0777, true);
        }

        $typeMigration = "t";

        if ((isset($argv[2])) && ($argv[2] == "s" || $argv[2] == "t")) {
            $typeMigration = $argv[2];
            array_splice($argv, 2, 1);
        }

        $nameMigration = $argv[2];
        $nameWithoutCounter = ucfirst($argv[2]);

        if ($typeMigration == "s") {
            $files = scandir(self::$pathMigration);
            $lastFile = end($files);

            $lastFile = explode("_", $lastFile);
            
            $counter = $lastFile[0] + 1;

            if (strlen($counter) == 1) $counter = "00" . $counter;
            if (strlen($counter) == 2) $counter = "0" . $counter;
            
            $nameMigration = $counter . "_" . $argv[2] . ".php";
        } else {
            $nameMigration = date('YmdHms') . "_" . $argv[2] . ".php";
        }

        $txtAttributes = "";
        $txtAttributesDown = "";
        if (isset($argv[3])) {
            $attributes = ltrim($argv[3], "[");
            $attributes = rtrim($attributes, "]");
            $attributes = explode(",", $attributes);

            $txtAttributes = "        \$this->dbforge->add_field(array(\n";
            $counterAttr = count($attributes) - 1;
            for ($i = 0; $i <= $counterAttr; $i++) { 
                if ($counterAttr == $i)
                    $txtAttributes .= "            '".$attributes[$i]."'" . " => array()\n";
                else
                    $txtAttributes .= "            '".$attributes[$i]."'" . " => array(),\n";
            }
            $txtAttributes .= "        ));\n\n";
            $txtAttributes .= "        \$this->dbforge->add_key('id', TRUE);\n";
            $txtAttributes .= "        \$this->dbforge->create_table('YOUR_TABLE');\n";

            $txtAttributesDown = "        \$this->dbforge->drop_table('YOUR_TABLE', TRUE);\n";
        }

        $newMigration = fopen(self::$pathMigration . $nameMigration, "w") or die("Unable to open file!");

        $txt = "<?php\n";
        $txt .= "defined('BASEPATH') OR exit('No direct script access allowed');\n\n";
        $txt .= "class Migration_". $nameWithoutCounter ." extends CI_Migration {\n\n";
        $txt .= "   public function up()\n";
        $txt .= "   {\n";
        $txt .=         $txtAttributes;
        $txt .= "   }\n\n";
        $txt .= "   public function down()\n";
        $txt .= "   {\n";
        $txt .=         $txtAttributesDown;
        $txt .= "   }\n";
        $txt .= "}";
        
        fwrite($newMigration, $txt);
        fclose($newMigration);

        echo "Migration created successfully.\n";
    }

    public static function createModel($argv)
    {
        if (!isset($argv[2])) {
            echo "Missing Model name\n";
            exit();
        }

        $nameModel = $argv[2];

        $attributes = "";
        for ($i = 3; $i < count($argv); $i++) { 
            $attributes .= "   public \$" . $argv[$i] . ";\n";
        }
        if (!empty($attributes)) $attributes .= "\n";

        $newModel = fopen(self::$pathModel.ucfirst($nameModel)."_model.php", "w") or die("Unable to open file!");

        $txt = "<?php\n";
        $txt .= "defined('BASEPATH') OR exit('No direct script access allowed');\n\n";
        $txt .= "class ".ucfirst($nameModel)."_model"." extends CI_Model {\n\n";
        $txt .= $attributes;
        $txt .= "   public function __construct()\n";
        $txt .= "   {\n";
        $txt .= "       parent::__construct();\n";
        $txt .= "   }\n";
        $txt .= "}";
        
        fwrite($newModel, $txt);
        fclose($newModel);

        echo "Model created successfully.\n";
    }

    public static function createController($argv)
    {
        if (!isset($argv[2])) {
            echo "Missing Controller name\n";
            exit();
        }
            
        $nameController = $argv[2];
        $extends = "CI_Controller";
        
        if (isset($argv[3]))
            $extends = $argv[3];

        $newController = fopen(self::$pathController.ucfirst($nameController).".php", "w") or die("Unable to open file!");

        $txt = "<?php\n";
        $txt .= "defined('BASEPATH') OR exit('No direct script access allowed');\n\n";
        $txt .= "class ".ucfirst($nameController)." extends ".$extends." {\n\n";
        $txt .= "   public function index()\n";
        $txt .= "   {\n";
        $txt .= "       \$this->load->view('welcome_message');  \n";
        $txt .= "   }\n";
        $txt .= "}";
        
        fwrite($newController, $txt);
        fclose($newController);
     
        echo "Controller created successfully.\n";
    }
}